source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SBRProjectBase_Example', :exclusive => true do
  pod 'SBRProjectBase', :path => '../'
end

target 'SBRProjectBase_Tests', :exclusive => true do
  pod 'SBRProjectBase', :path => '../'

  
end
